import { useState } from 'react';

import Head from 'next/head';

import Loading from '../components/Loading';
import SkeletonContent from '../components/SkeletonContent';

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [message, setMessage] = useState('');

  let account = '';

  const connectWallet = () => {};

  const hello = () => {};

  const handleMessage = (event) => {
    const value = event.target.value;
    setMessage(value);
  };

  return (
    <div className="max-w-2xl mx-auto">
      <Head>
        <title>
          Hello World Rust | Challenge #2 - Hello World Smart Contract
        </title>
        <meta
          name="description"
          content="Challenge #2 - Hello World Smart Contract | Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-24">
        <h1 className="text-slate-900 font-extrabold text-4xl sm:text-5xl lg:text-6xl tracking-tight text-center">
          👋 Hello NEAR!
        </h1>

        {!account ? (
          <div className="inset-x-0 flex justify-center pt-8 mb-16">
            <button
              className="bg-slate-800 hover:bg-slate-600 text-white font-semibold h-12 px-6 rounded-lg w-full flex items-center justify-center sm:w-auto"
              onClick={connectWallet}
            >
              Connect Wallet
            </button>
          </div>
        ) : (
          <p className="mt-4 mb-8 mx-auto">
            <strong>Hello, </strong> {account}
          </p>
        )}

        <hr className="my-24 max-w-sm mx-auto" />

        <div className="max-w-sm mx-auto">
          <textarea
            rows="1"
            onChange={handleMessage}
            value={message}
            placeholder="Please leave your name :)"
            className="p-4 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md"
          ></textarea>

          <div className="text-right mt-4 mb-24">
            {isLoading ? (
              <Loading />
            ) : (
              <button
                className="rounded-md py-2 px-4 border-transparent bg-indigo-700 hover:bg-indigo-600 text-slate-200 font-medium disabled:bg-indigo-200"
                onClick={hello}
                disabled={!account}
              >
                Send a message
              </button>
            )}
          </div>
        </div>
      </main>

      <footer className="pt-16 text-center leading-4 text-slate-700">
        <p>
          NEAR Hello World App with Rust + Next.js
          {` | `}
          <a
            className="text-teal-500"
            href="https://github.com/Phonbopit/near-helloworld-app"
          >
            Source Code
          </a>
        </p>
      </footer>
    </div>
  );
}
